name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-26

    steps:
    - uses: actions/checkout@v7
    - name: sw_vers
      run: sw_vers
    - name: Available Xcodes
      run: ls /Applications | grep Xcode
    - name: Switch to Xcode
      run: sudo xcode-select -s "/Applications/Xcode_26.5.app/Contents/Developer"
    - name: Xcode - Accept License
      run: sudo xcodebuild -license accept
    - name: Xcode - First Launch
      run: xcodebuild -runFirstLaunch
    - name: Xcode Version
      run: xcodebuild -version
